version: '3.8'

services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: ../deployment/docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000/api
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - agarwal-network

  backend:
    build:
      context: ../../backend
      dockerfile: ../deployment/docker/Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/agarwal_sabha
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - db
    networks:
      - agarwal-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: agarwal_sabha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agarwal-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - agarwal-network

volumes:
  postgres_data:

networks:
  agarwal-network:
    driver: bridge
